### ISSUE TITLE
Deploy to Maven central

### ISSUE THREAD

**Issue by trajano** [ymasory/OrangeExtensions#3]
Is it possible to have this deployed to Maven central repository

**Comment by ymasory** [comment]
I deployed to Sonatype. https://oss.sonatype.org/content/repositories/releases/com/yuvimasory/orange-extensions/
I requested they turn on synchronization to Maven central, so let's see how long that takes. Hopefully in a day or two it will be in maven central :)

**Comment by ymasory** [comment]
This is now available in maven central, http://central.maven.org/maven2/com/yuvimasory/orange-extensions/
