### ISSUE TITLE
problems with maven central artifacts

### ISSUE THREAD

**Issue by jtomson** [ymasory/OrangeExtensions#5]
Hello - firstly thanks for providing these stubs and making them so accessible. However I tried to make use of the artifacts on maven central and ran into two things:
1. The jar seems to be empty aside from the manifest?

``` bash
$ jar vtf orange-extensions-1.0.0.jar 
   286 Tue Sep 25 13:06:26 EDT 2012 META-INF/MANIFEST.MF
```
1. The `pom` file lists scala as a dependency, which is unnecessary

``` xml
...
<dependency>
<groupId>org.scala-lang</groupId>
<artifactId>scala-library</artifactId>
<version>2.9.2</version>
<scope>compile</scope>
</dependency>
...
```

Downloading the 1.2 jar file from github works like a charm though - thanks again for your work.

**Comment by ymasory** [comment]
That's a good point, thanks. I'll fix it.

**Comment by ymasory** [comment]
I've got it fixed in the repo. Now just dealing with sbt configurations to make sure it passes Maven Central requirements.

**Comment by ymasory** [comment]
All done! Use version 1.3.0 and all should be well. It's available on Sonatype (https://oss.sonatype.org/content/repositories/releases/com/yuvimasory/orange-extensions/1.3.0/) and will sync to Maven Central within 2 hours (http://central.maven.org/maven2/com/yuvimasory/orange-extensions/).

**Comment by jtomson** [comment]
Awesome - just got a chance to try the new 1.3.0 artifacts and they work great. Thanks for the quick turnaround!
